{% set version = "2022.6.1" %}


package:
  name: dask-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 6ecc4571da3e5575dd1fa1537237434908f81b929f7f2a3493a7f6eb8507903e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - packaging >=20.0
    - partd >=0.3.10
    - pyyaml >=5.3.1
    - toolz >=0.8.2

test:
  imports:
    - dask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/dask/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
