{% set version = "2024.11.2" %}
{% set python_min = "3.10" %}


package:
  name: dask-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 9a72bee3f149ff89bc492340d4bcba33d5dd3e3a9d471d2b4b3872f2d71ddaae

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask = dask.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer =0.29
    - tomli

  run:
    - python >={{ python_min }}
    - click >=8.1
    - cloudpickle >=3.0.0
    - fsspec >=2021.09.0
    - packaging >=20.0
    - partd >=1.4.0
    - pyyaml >=5.3.1
    - toolz >=0.10.0
    - importlib-metadata >=4.13.0

test:
  imports:
    - dask
  commands:
    - pip check
    - dask --help
    - dask docs --help
    - dask info --help
    - dask info versions --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dask/dask/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
    - charlesbluca
    - fjetter
