{% set version = "2.25.0" %}

package:
  name: dask-core
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 12ac2ee71157b8eecb89b48cd2aa0be7b1b4bb90a791d3e8d6c4002cdc9499e3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - dask

about:
  home: http://github.com/dask/dask/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
