{% set version = "0.15.3" %}

package:
  name: dask-core
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 439316a7f603785b1afe2592b2be244cb8d1a272d1a28b93042367be65082786

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - dask

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Parallel Python with task scheduling'

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
