{% set version = "0.17.5" %}

package:
  name: dask-core
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: ea8ad7735048a6e8a9e389186f840a0a9e5c5eeb55379c8b3c9d4883be863c5c

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - dask

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Parallel Python with task scheduling'
  doc_url: https://dask.pydata.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - ogrisel
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
